project_id = "eventglow"

[functions.send-push]
verify_jwt = false

[functions.create-user-admin]
verify_jwt = false

[functions.paystack-init]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false
